# Generated by Django 5.1 on 2024-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_life', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
